# .github/workflows/dev.yml
name: Dev CI/CD

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build, lint, test (optional)

      # Build Docker images
      - run: docker build -t myrepo/tokenizer-backend:dev ./backend
      - run: docker build -t myrepo/tokenizer-frontend:dev ./frontend

      # Login and push to registry (use :dev tag)
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push myrepo/tokenizer-backend:dev
      - run: docker push myrepo/tokenizer-frontend:dev

      # Optional: Deploy to dev server
      # - uses: appleboy/ssh-action@v0.1.10
      #   with: ... (dev server details)
